function initCopyright() {
    var date=new Date();
    year=date.getFullYear();
    syear=new String(year);

    document.writeln("<!--Copyright-->");
    document.writeln("<div style=\"width: 100%;text-align: center;\">");
    document.writeln("     <p class=\"copyright\">Copyright © "+syear+"&nbsp;<a target=\"_blank\" href=\"index.html\" style=\"color: white;font-size: 15px;\">山东省济南市章丘区第四中学高一六班</a>保留所有权利|鲁ICP备 NULL|<a target=\"_blank\" href=\"about.html\" style=\"color: white;font-size: 15px;\">关于</a></p>");
    document.writeln("</div>");
}

function initCSS() {
    document.writeln("<!--导入CSS-->");
    document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainstyle.css\" id=\"normalStyle\">");
    document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mcStyle.css\" id=\"MCStyle\" DISABLED>");
    document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mcFont.css\">");
}
function cloudKeyWordsImage() {
    document.write("<html>");
    document.write("                <head>");
    document.write("                    <meta charset=\"UTF-8\">");
    document.write("                    <script type=\"text\/javascript\" src=\"https:\/\/assets.pyecharts.org\/assets\/v5\/echarts.min.js\"><\/script>");
    document.write("                    <script type=\"text\/javascript\" src=\"https:\/\/assets.pyecharts.org\/assets\/v5\/echarts-wordcloud.min.js\"><\/script>");
    document.write("");
    document.write("                <\/head>");
    document.write("                <body >");
    document.write("                    <div id=\"d0b6dd08e72a4188819ae749e005d5e2\" class=\"chart-container\" style=\"width:900px; height:500px; \"><\/div>");
    document.write("                    <script>");
    document.write("                        var chart_d0b6dd08e72a4188819ae749e005d5e2 = echarts.init(");
    document.write("                            document.getElementById('d0b6dd08e72a4188819ae749e005d5e2'), 'white', {renderer: 'canvas'});");
    document.write("                        var option_d0b6dd08e72a4188819ae749e005d5e2 = {");
    document.write("                    \"animation\": true,");
    document.write("                    \"animationThreshold\": 2000,");
    document.write("                    \"animationDuration\": 1000,");
    document.write("                    \"animationEasing\": \"cubicOut\",");
    document.write("                    \"animationDelay\": 0,");
    document.write("                    \"animationDurationUpdate\": 300,");
    document.write("                    \"animationEasingUpdate\": \"cubicOut\",");
    document.write("                    \"animationDelayUpdate\": 0,");
    document.write("                    \"aria\": {");
    document.write("                        \"enabled\": false");
    document.write("                    },");
    document.write("                    \"color\": [");
    document.write("                        \"#5470c6\",");
    document.write("                        \"#91cc75\",");
    document.write("                        \"#fac858\",");
    document.write("                        \"#ee6666\",");
    document.write("                        \"#73c0de\",");
    document.write("                        \"#3ba272\",");
    document.write("                        \"#fc8452\",");
    document.write("                        \"#9a60b4\",");
    document.write("                        \"#ea7ccc\"");
    document.write("                    ],");
    document.write("                    \"series\": [");
    document.write("                        {");
    document.write("                            \"type\": \"wordCloud\",");
    document.write("                            \"shape\": \"circle\",");
    document.write("                            \"rotationRange\": [");
    document.write("                                -90,");
    document.write("                                90");
    document.write("                            ],");
    document.write("                            \"rotationStep\": 45,");
    document.write("                            \"girdSize\": 20,");
    document.write("                            \"sizeRange\": [");
    document.write("                                20,");
    document.write("                                80");
    document.write("                            ],");
    document.write("                            \"data\": [");
    document.write("                                {");
    document.write("                                    \"name\": \"\u9ad8\u4e00\u516d\u73ed\",");
    document.write("                                    \"value\": 10,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(97,60,148)\"");
    document.write("                                    }");
    document.write("                                },");
    document.write("                                {");
    document.write("                                    \"name\": \"\u91d1\u5149\u4e94\u661f\u4e50\u961f\",");
    document.write("                                    \"value\": 6,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(37,58,2)\"");
    document.write("                                    }");
    document.write("                                },");
    document.write("                                {");
    document.write("                                    \"name\": \"\u9633\u5149\u5f00\u6717\",");
    document.write("                                    \"value\": 4,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(43,79,154)\"");
    document.write("                                    }");
    document.write("                                },");
    document.write("                                {");
    document.write("                                    \"name\": \"\u79ef\u6781\u5411\u4e0a\",");
    document.write("                                    \"value\": 3,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(68,49,21)\"");
    document.write("                                    }");
    document.write("                                },");
    document.write("                                {");
    document.write("                                    \"name\": \"\u4e00\u8eab\u6b63\u6c14\",");
    document.write("                                    \"value\": 3,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(58,41,25)\"");
    document.write("                                    }");
    document.write("                                },");
    document.write("                                {");
    document.write("                                    \"name\": \"605\",");
    document.write("                                    \"value\": 2,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(149,160,75)\"");
    document.write("                                    }");
    document.write("                                },");
    document.write("                                {");
    document.write("                                    \"name\": \"\u51ef\u54e5\",");
    document.write("                                    \"value\": 2,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(105,28,12)\"");
    document.write("                                    }");
    document.write("                                },");
    document.write("                                {");
    document.write("                                    \"name\": \"\u7ae0\u4e18\u56db\u4e2d\",");
    document.write("                                    \"value\": 1,");
    document.write("                                    \"textStyle\": {");
    document.write("                                        \"color\": \"rgb(65,29,133)\"");
    document.write("                                    }");
    document.write("                                }");
    document.write("                            ],");
    document.write("                            \"drawOutOfBound\": false,");
    document.write("                            \"textStyle\": {");
    document.write("                                \"emphasis\": {}");
    document.write("                            },");
    document.write("                            \"label\": {");
    document.write("                                \"show\": false,");
    document.write("                                \"margin\": 8");
    document.write("                            },");
    document.write("                            \"rippleEffect\": {");
    document.write("                                \"show\": true,");
    document.write("                                \"brushType\": \"stroke\",");
    document.write("                                \"scale\": 2.5,");
    document.write("                                \"period\": 4");
    document.write("                            }");
    document.write("                        }");
    document.write("                    ],");
    document.write("                    \"legend\": [");
    document.write("                        {");
    document.write("                            \"data\": [],");
    document.write("                            \"selected\": {},");
    document.write("                            \"show\": true,");
    document.write("                            \"padding\": 5,");
    document.write("                            \"itemGap\": 10,");
    document.write("                            \"itemWidth\": 25,");
    document.write("                            \"itemHeight\": 14,");
    document.write("                            \"backgroundColor\": \"transparent\",");
    document.write("                            \"borderColor\": \"#ccc\",");
    document.write("                            \"borderWidth\": 1,");
    document.write("                            \"borderRadius\": 0,");
    document.write("                            \"pageButtonItemGap\": 5,");
    document.write("                            \"pageButtonPosition\": \"end\",");
    document.write("                            \"pageFormatter\": \"{current}\/{total}\",");
    document.write("                            \"pageIconColor\": \"#2f4554\",");
    document.write("                            \"pageIconInactiveColor\": \"#aaa\",");
    document.write("                            \"pageIconSize\": 15,");
    document.write("                            \"animationDurationUpdate\": 800,");
    document.write("                            \"selector\": false,");
    document.write("                            \"selectorPosition\": \"auto\",");
    document.write("                            \"selectorItemGap\": 7,");
    document.write("                            \"selectorButtonGap\": 10");
    document.write("                        }");
    document.write("                    ],");
    document.write("                    \"tooltip\": {");
    document.write("                        \"show\": true,");
    document.write("                        \"trigger\": \"item\",");
    document.write("                        \"triggerOn\": \"mousemove|click\",");
    document.write("                        \"axisPointer\": {");
    document.write("                            \"type\": \"line\"");
    document.write("                        },");
    document.write("                        \"showContent\": true,");
    document.write("                        \"alwaysShowContent\": false,");
    document.write("                        \"showDelay\": 0,");
    document.write("                        \"hideDelay\": 100,");
    document.write("                        \"enterable\": false,");
    document.write("                        \"confine\": false,");
    document.write("                        \"appendToBody\": false,");
    document.write("                        \"transitionDuration\": 0.4,");
    document.write("                        \"textStyle\": {");
    document.write("                            \"fontSize\": 14");
    document.write("                        },");
    document.write("                        \"borderWidth\": 0,");
    document.write("                        \"padding\": 5,");
    document.write("                        \"order\": \"seriesAsc\"");
    document.write("                    },");
    document.write("                    \"title\": [");
    document.write("                        {");
    document.write("                            \"show\": true,");
    document.write("                            \"target\": \"blank\",");
    document.write("                            \"subtarget\": \"blank\",");
    document.write("                            \"padding\": 5,");
    document.write("                            \"itemGap\": 10,");
    document.write("                            \"textAlign\": \"auto\",");
    document.write("                            \"textVerticalAlign\": \"auto\",");
    document.write("                            \"triggerEvent\": false");
    document.write("                        }");
    document.write("                    ]");
    document.write("                };");
    document.write("                        chart_d0b6dd08e72a4188819ae749e005d5e2.setOption(option_d0b6dd08e72a4188819ae749e005d5e2);");
    document.write("                    <\/script>");
    document.write("                <\/body>");
    document.write("            <\/html>");
}